name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Athenticate
        run: dotnet nuget add source
          --username EvaldasZmitra
          --password ${{ secrets.PACKAGE_READER }}
          --store-password-in-clear-text
          --name github "https://nuget.pkg.github.com/EvaldasZmitra/index.json"
        shell: bash

      - name: Restore dependencies
        run: dotnet restore
        shell: bash

      - name: Build
        run: dotnet build -c Release --no-restore
        shell: bash

      - name: Test
        run: dotnet test
          -c Release
          --no-build
          --collect:"XPlat Code Coverage"
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        shell: bash

      - name: Package
        run: dotnet pack
          -c Release
          --no-build
          -o out
          -p:PackageVersion=${{ steps.version.outputs.version }}
        shell: bash

      - name: Athenticate For Push
        run: dotnet nuget update source github
          --username EvaldasZmitra
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
        shell: bash

      - name: Publish to github packages
        run: dotnet nuget push
          --skip-duplicate
          "out/ez-bitpacker.${{ steps.version.outputs.version }}.nupkg"
          -s github
        shell: bash

      - name: Publish to nuget
        run: dotnet nuget push
          --skip-duplicate
          "out/ez-bitpacker.${{ steps.version.outputs.version }}.nupkg"
          -k ${{ secrets.NUGET_SERVER_KEY }}
          -s https://api.nuget.org/v3/index.json
        shell: bash
